- name: RUN COMMAND FOR CONFIGURE FILE
  hosts: vthunder
  gather_facts: false
  become: True
  tasks:
    - name: Run commands from lines
      a10.acos_cli.acos_command:
        commands: show running-config

